// Mocks generated by Mockito 5.1.0 from annotations
// in upwind/test/services/connection_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:connectivity_plus/connectivity_plus.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:upwind/src/repositories/connection_repository/connection_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ConnectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionRepository extends _i1.Mock
    implements _i2.ConnectionRepository {
  MockConnectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.ConnectivityResult> getConnectionStream() =>
      (super.noSuchMethod(Invocation.method(#getConnectionStream, []),
              returnValue: Stream<_i4.ConnectivityResult>.empty())
          as _i3.Stream<_i4.ConnectivityResult>);
}
